# Generated by Django 3.1.6 on 2021-02-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210209_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=-3915, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
