# Generated by Django 3.1.6 on 2021-02-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210209_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
