# Generated by Django 3.1.6 on 2021-02-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
