# Generated by Django 3.1.6 on 2021-02-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210219_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custom_notes',
            new_name='custom_links',
        ),
    ]
