# Generated by Django 3.1.6 on 2021-04-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210219_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fulfilled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0.01, help_text='Price per gram (ppg) of the material. Either pre- or post-markup can be used here, but be consistent.', max_digits=4, verbose_name='Price per gram'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('O', 'Ordered'), ('NQ', 'Needs Quote'), ('QS', 'Quote Sent'), ('P', 'Paid'), ('I', 'In Progress'), ('R', 'Ready For Pickup'), ('F', 'Fulfilled'), ('C', 'Cancelled')], default='O', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price_multiplier',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Enter the additional markup multiplier across all materials for this product.', max_digits=4),
        ),
    ]
